language: node_js

node_js:
  - "8.16.0"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng build --prod

deploy:
  provider: elasticbeanstalk
  access_key_id: "AKIAIKYPGN6QNLOKPV5Q"
  secret_access_key:
    secure: "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"
  region: "eu-central-1"
  local_dir: backend
  app: "expedio"
  env: "Expedio-environment"
  bucket_name: "expedio-environment.trwa4fmphr.eu-central-1"
  skip_cleanup: true
  on:
    branch: develop

after_deploy:
  - echo "Expedio App Deployed"

notifications:
  email:
    on_failure: change
    on_success: change
