language: node_js

node_js:
  - "10"

branches:
  only:
    - develop

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng build --prod

before_deploy:
  - cd backend
  - ls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: $SECRET_ACCESS_KEY
  region: "eu-central-1"
  app: "expedio"
  env: "Expedio-environment"
  bucket_name: $BUCKET_NAME
  skip_cleanup: true
  on:
    branch: develop

after_deploy:
  - echo "Expedio App Deployed"

notifications:
  email:
    on_failure: change
    on_success: change
