language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

install:
  - npm install -g @angular/cli
  - npm install
  - cd backend && npm install

script:
  - npm run prod

deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_API_KEY
    app: expedio
    skip_cleanup: true
    local_dir: backend
    on:
      repo: AndreiMLazar/Expedio
      all_branches: true

after_deploy:
  - echo "Expedio Deployed"

notifications:
  email:
    on_failure: change
    on_success: change
