language: node_js

node_js:
  - "10"

branches:
  only:
    - develop

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli
  - npm install
  - npm version patch

script:
  - then ng build --prod

deploy:
  - provider: heroku
    api_key:
      secure: $HEROKU_API_KEY
    skip_cleanup: true
    local_dir: backend
    on:
      branch: develop

after_deploy:
  - echo "Expedio Deployed"

notifications:
  email:
    on_failure: change
    on_success: change
